version: "3"

services:
  redis:
    image: redis
    container_name: redis_cache
    ports:
      - 6379:6379
    networks:
      - net

  # server:
  #   build: ./server
  #   container_name: server
  #   environment:
  #     - REDIS_URL=redis://redis
  #   ports:
  #     - 8008:3000
  #   networks:
  #     - net

  # client:
  #   build: ./web
  #   container_name: client
  #   environment:
  #     - NEXT_PUBLIC_API_BASE_URL=http://server:8008
  #   ports:
  #     - 8080:3000
  #   networks:
  #     - net

networks:
  net:
    driver: bridge
