version: "3"

services:
  redis:
    image: redis
    container_name: redis_cache
    ports:
      - 6379:6379
    networks:
      - net

  server:
    build: ./server
    container_name: server
    env_file: ./server/.env
    ports:
      - 8008:3000
    networks:
      - net

  client:
    build: ./web
    container_name: client
    environment:
      - NG_APP_SERVER_URL=http://server:8008
    ports:
      - 8080:4200
    networks:
      - net

networks:
  net:
    driver: bridge
